# Generated by Django 4.2 on 2023-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_alter_order_status_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="avatar",
            field=models.ImageField(upload_to="delivery-system-image/"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="avatar",
            field=models.ImageField(upload_to="delivery-system-image/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="product_img",
            field=models.ImageField(upload_to="delivery-system-image/"),
        ),
        migrations.AlterField(
            model_name="shipper",
            name="avatar",
            field=models.ImageField(upload_to="delivery-system-image/"),
        ),
    ]
