# Generated by Django 4.2 on 2023-08-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_alter_admin_avatar_alter_customer_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="avatar",
            field=models.ImageField(upload_to="delivery-system-image/"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="avatar",
            field=models.ImageField(upload_to="delivery-system-image/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="product_img",
            field=models.ImageField(upload_to="delivery-system-image/"),
        ),
        migrations.AlterField(
            model_name="shipper",
            name="avatar",
            field=models.ImageField(upload_to="delivery-system-image/"),
        ),
    ]
