"""
Django settings for delivery_system project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(ju)l4sd(^+1tz7p(&sx*#tme=n73drkdr#1nru0cck&8129a3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['tat2501.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'oauth2_provider',
    'delivery.apps.DeliveryConfig',
    'rest_framework',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ]
}

OAUTH2_PROVIDER = {
    # parses OAuth2 data from application/json requests
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'delivery_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'delivery_system.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import pymysql

pymysql.install_as_MySQLdb()


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tat2501$deliverydb',
        'USER': 'tat2501',
        'PASSWORD': '123456aT@',
        'HOST': 'tat2501.mysql.pythonanywhere-services.com'  # mặc định localhost
    }
}

AUTH_USER_MODEL = 'delivery.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATIC_URL = '/static/'

MEDIA_ROOT = '%s/delivery_system/static/' % BASE_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Jazzmin Setting
JAZZMIN_SETTINGS = {
    "site_title": "Delivery Admin",
    "site_brand": "Delivery Manager System",
    "site_icon": 'avatar/logo_delivery.jpg',
    "welcome_sign": "Welcome to the Delivery System",
    "copyright": "TAT1902",

    "icons": {
        "auth": "fas fa-users-cog",
        "delivery.User": "fas fa-user",
        "delivery.Admin": "fas fa-user-tie",
        "delivery.Shipper": "fas fa-user-astronaut",
        "delivery.Customer": "fas fa-users",
        "delivery.Auction": "fas fa-coins",
        "delivery.Discount": "fas fa-tag",
        "delivery.Order": "fas fa-sort",
        "delivery.Post": "fas fa-blog",
        "delivery.Rating": "fas fa-star",
        "delivery.Comment": "fas fa-comment"
    }
}

JAZZMIN_UI_TWEAKS = {
    "theme": "sketchy",
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_INFO = {
    'client_id': '9vhHlCjWFLyjziLLorgcD2c0JHVsi4l9Tttngjph',
    'client_secret': 'KXW7Jesp2Lm4xo7OYMKWmLyHqK5lT4gCmx3fnMdJIfW1E4w1usCFpaJumKjahF8mwxCCUlAICp2Pgb1vdhZEA15NgYeblaIQURIdhJM1CXtzE4b7BjrOBjl1MhO9OvwK',
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "testcode190201@gmail.com"
EMAIL_HOST_PASSWORD = "nscihqbdcjcsdqbz"
